"""Generate the repository's standalone supplementary figures.

The primary D2-D7 analysis figures remain reproducible from A2_analysis.ipynb.
This single entry point owns the figures that are not generated by that
notebook, avoiding one small script per chart.

Run: python3 generate_plots.py
"""

import json
import os
from collections import Counter
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", "/tmp/pe6201-matplotlib")
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from d6_cost_model import RUNS, measure_run


ROOT = Path(__file__).resolve().parent
RESULTS = ROOT / "results"
FIGS = ROOT / "figs"
BLUE = "#78A6C8"
LIGHT_BLUE = "#A8C7DD"
CORAL = "#E07A5F"
NAVY = "#273043"
GREY = "#8B9098"
B = 2165
D = 176


def save(fig, filename):
    FIGS.mkdir(exist_ok=True)
    path = FIGS / filename
    fig.savefig(path, dpi=180, bbox_inches="tight")
    plt.close(fig)
    print("plot written to", path)


def completed_task_cost_plot():
    rows = []
    for label, (model, filename) in RUNS.items():
        if "v1 prompt" in label:
            continue
        measured = measure_run(model, filename)
        result_rows = json.loads((RESULTS / filename).read_text())
        negative = [
            row for row in result_rows
            if row["expected"] != "approve_in_principle"
        ]
        p = sum(bool(row["passed"]) for row in negative) / len(negative)
        rows.append((label, measured["l1"], p))

    x = list(range(len(rows)))
    width = 0.36
    fig, ax = plt.subplots(figsize=(10.5, 5.8))
    ax.bar([i - width / 2 for i in x], [r[1] for r in rows], width,
           label="Measured token cost / run", color=BLUE)
    completed = [cost / p for _, cost, p in rows]
    ax.bar([i + width / 2 for i in x], completed, width,
           label="Cost / completed output (C / p)", color=CORAL)
    ax.set_xticks(x, [r[0].replace("-instruct", "") for r in rows],
                  rotation=18, ha="right")
    ax.set_ylabel("US dollars")
    ax.set_title("Completed-task cost: failed runs raise the cost of useful output")
    ax.grid(axis="y", alpha=0.25)
    ax.legend(frameon=False)
    for i, ((_, _, p), value) in enumerate(zip(rows, completed)):
        ax.text(i + width / 2, value + 0.00008,
                "${:.4f}\n(p={:.1%})".format(value, p),
                ha="center", va="bottom", fontsize=8)
    ax.text(0.01, -0.31,
            "C/p assumes failed runs are retried. D6 instead prices escalation "
            "as C + (1-p) x $7.60; the two answer different questions.",
            transform=ax.transAxes, fontsize=9, color="#444444")
    fig.tight_layout()
    save(fig, "fig_d0_class4_bill_test.png")


def predicted_input(turns):
    return B * turns + D * turns * (turns - 1) / 2


def turn_token_growth_plot():
    turns = list(range(1, 17))
    prefix = [B * t for t in turns]
    history = [D * t * (t - 1) / 2 for t in turns]
    totals = [predicted_input(t) for t in turns]
    fig, ax = plt.subplots(figsize=(10.5, 5.8))
    ax.stackplot(turns, prefix, history,
                 labels=["Repeated base prompt: B x T",
                         "Accumulated history: D x T(T-1) / 2"],
                 colors=[BLUE, CORAL], alpha=0.9)
    ax.plot(turns, totals, color=NAVY, linewidth=2.2, marker="o",
            markersize=3, label="Total predicted input")
    for turn in (4, 8, 16):
        total = predicted_input(turn)
        ax.annotate(f"{turn} turns\n{total:,.0f} tokens", (turn, total),
                    xytext=((-28 if turn == 16 else 0), 10),
                    textcoords="offset points", ha="center", fontsize=9,
                    fontweight="bold")
    ratio = predicted_input(16) / predicted_input(8)
    ax.text(0.02, 0.94, f"8 -> 16 turns: {ratio:.1f}x input tokens",
            transform=ax.transAxes, fontsize=11, fontweight="bold",
            bbox={"boxstyle": "round,pad=0.35", "facecolor": "white",
                  "edgecolor": "#777777", "alpha": 0.9})
    ax.set_title("Input-token growth as agent turns increase")
    ax.set_xlabel("Agent turns (T)")
    ax.set_ylabel("Predicted input tokens across one run")
    ax.set_xticks(turns)
    ax.set_ylim(0, max(totals) * 1.08)
    ax.grid(axis="y", alpha=0.25)
    ax.legend(frameon=False, loc="upper left", bbox_to_anchor=(0, 0.84))
    ax.text(0.01, -0.20,
            "Formula: B x T + D x T(T-1)/2. Measured B = 2,165; "
            "representative D = 176 tokens/turn (median, parallel trajectories).",
            transform=ax.transAxes, fontsize=9, color="#444444")
    fig.tight_layout()
    save(fig, "fig_d0_turn_token_growth.png")


def strict_case_rate(rows):
    by_case = {}
    for row in rows:
        by_case.setdefault(row["case_id"], []).append(row)
    return 100 * sum(all(r["passed"] for r in case)
                     for case in by_case.values()) / len(by_case)


def historical_d5_plots():
    before = json.loads(
        (RESULTS / "d5b_live_gpt4o_mini_full_battery.json").read_text())
    after = json.loads(
        (RESULTS / "d5b_live_validation_after_prompt_fix.json").read_text())
    before_rate, after_rate = strict_case_rate(before), strict_case_rate(after)
    before_turns = sorted(r["steps"] for r in before)[len(before) // 2]
    after_turns = sorted(r["steps"] for r in after)[len(after) // 2]

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
    axes[0].bar(["before fix", "after fix"], [before_rate, after_rate],
                color=[CORAL, BLUE])
    axes[0].set_ylim(0, 100)
    axes[0].set_ylabel("strict case-consistency rate (%)")
    axes[0].set_title("D5(b) - GPT-4o-mini outcome consistency")
    for i, value in enumerate((before_rate, after_rate)):
        axes[0].text(i, value + 1, f"{value:.0f}%", ha="center")
    axes[1].bar(["before fix", "after fix"], [before_turns, after_turns],
                color=[CORAL, BLUE])
    axes[1].axhline(5, linestyle="--", color=GREY,
                    label="scripted assumption (5)")
    axes[1].set_ylabel("median turns")
    axes[1].set_title("D5(b) - median turns vs. scripted assumption")
    axes[1].legend()
    for i, value in enumerate((before_turns, after_turns)):
        axes[1].text(i, value + 0.1, str(value), ha="center")
    fig.tight_layout()
    save(fig, "fig_d5b_before_after.png")

    failures = [row for row in after if not row["passed"]]
    reasons = Counter(row.get("stop_reason") or "unknown" for row in failures)
    fig, ax = plt.subplots(figsize=(6.5, 4.5))
    labels, values = list(reasons), list(reasons.values())
    ax.bar(labels, values, color=CORAL)
    ax.set_ylabel("failing trials")
    ax.set_title("D5(b) - why the remaining failures happen")
    ax.tick_params(axis="x", rotation=18)
    for i, value in enumerate(values):
        ax.text(i, value + 0.15, str(value), ha="center")
    fig.tight_layout()
    save(fig, "fig_d5b_failure_reasons.png")


def main():
    completed_task_cost_plot()
    turn_token_growth_plot()
    historical_d5_plots()


if __name__ == "__main__":
    main()
