"""Generate the repository's standalone supplementary figures.

The primary D2-D7 analysis figures remain reproducible from A2_analysis.ipynb.
This single entry point owns the figures that are not generated by that
notebook, avoiding one small script per chart.

Run: python3 generate_plots.py
"""

import json
import math
import os
from collections import Counter
from pathlib import Path

os.environ.setdefault("MPLCONFIGDIR", "/tmp/pe6201-matplotlib")
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

import config
from d6_cost_model import (
    RUNS, measure_run, layer2_fallback, cost_per_successful_task,
    monthly_cost, break_even_success_rate, VOLUME_PER_MONTH,
)
from measure_parallel import measure_all


ROOT = Path(__file__).resolve().parent
RESULTS = ROOT / "results"
FIGS = ROOT / "figs"
BLUE = "#78A6C8"
LIGHT_BLUE = "#A8C7DD"
CORAL = "#E07A5F"
NAVY = "#273043"
GREY = "#8B9098"
# Measured from the live system prompt, not hardcoded - a hardcoded B here
# went stale the moment TOOL_SPECS's prompt_guidance changed (D4's gate-fix
# work grew it), which silently disagreed with every other B in the report.
B = round(len(config.build_system_prompt()) / 4)
D = 176


def save(fig, filename):
    FIGS.mkdir(exist_ok=True)
    path = FIGS / filename
    fig.savefig(path, dpi=180, bbox_inches="tight")
    plt.close(fig)
    print("plot written to", path)


def completed_task_cost_plot():
    rows = []
    for label, (model, filename) in RUNS.items():
        if "v1 prompt" in label:
            continue
        measured = measure_run(model, filename)
        result_rows = json.loads((RESULTS / filename).read_text())
        negative = [
            row for row in result_rows
            if row["expected"] != "approve_in_principle"
        ]
        p = sum(bool(row["passed"]) for row in negative) / len(negative)
        rows.append((label, measured["l1"], p))

    x = list(range(len(rows)))
    width = 0.36
    fig, ax = plt.subplots(figsize=(10.5, 5.8))
    ax.bar([i - width / 2 for i in x], [r[1] for r in rows], width,
           label="Measured token cost / run", color=BLUE)
    completed = [cost / p for _, cost, p in rows]
    ax.bar([i + width / 2 for i in x], completed, width,
           label="Cost / completed output (C / p)", color=CORAL)
    ax.set_xticks(x, [r[0].replace("-instruct", "") for r in rows],
                  rotation=18, ha="right")
    ax.set_ylabel("US dollars")
    ax.set_title("Completed-task cost: failed runs raise the cost of useful output")
    ax.grid(axis="y", alpha=0.25)
    ax.legend(frameon=False)
    for i, ((_, _, p), value) in enumerate(zip(rows, completed)):
        ax.text(i + width / 2, value + 0.00008,
                "${:.4f}\n(p={:.1%})".format(value, p),
                ha="center", va="bottom", fontsize=8)
    ax.text(0.01, -0.31,
            "C/p assumes failed runs are retried. D6 instead prices escalation "
            "as C + (1-p) x $7.60; the two answer different questions.",
            transform=ax.transAxes, fontsize=9, color="#444444")
    fig.tight_layout()
    save(fig, "fig_d0_class4_bill_test.png")


def predicted_input(turns):
    return B * turns + D * turns * (turns - 1) / 2


def turn_token_growth_plot():
    turns = list(range(1, 17))
    prefix = [B * t for t in turns]
    history = [D * t * (t - 1) / 2 for t in turns]
    totals = [predicted_input(t) for t in turns]
    fig, ax = plt.subplots(figsize=(10.5, 5.8))
    ax.stackplot(turns, prefix, history,
                 labels=["Repeated base prompt: B x T",
                         "Accumulated history: D x T(T-1) / 2"],
                 colors=[LIGHT_BLUE, "#F2B7A8"], alpha=0.55)
    ax.plot(turns, totals, color=NAVY, linewidth=2.5,
            label="Total predicted input")
    offsets = {4: (-34, 14), 8: (10, 14), 16: (-92, -36)}
    for turn in (4, 8, 16):
        total = predicted_input(turn)
        is_measured = turn == 8
        ax.scatter([turn], [total], color=(CORAL if is_measured else BLUE),
                   s=100 if is_measured else 65, zorder=6,
                   edgecolor="white", linewidth=1.2)
        label = (f"T={turn}: {total:,.0f} tokens\n"
                 + ("representative point" if is_measured else "predicted"))
        ax.annotate(label, (turn, total), xytext=offsets[turn],
                    textcoords="offset points", ha="left", fontsize=8.8,
                    fontweight="bold" if is_measured else "normal",
                    color=(CORAL if is_measured else NAVY))
    ax.axvline(8, color=CORAL, linestyle="--", linewidth=1, alpha=0.75)
    ratio = predicted_input(16) / predicted_input(8)
    ax.text(0.02, 0.94, f"8 -> 16 turns: {ratio:.1f}x input tokens",
            transform=ax.transAxes, fontsize=10, fontweight="bold",
            bbox={"boxstyle": "round,pad=0.35", "facecolor": "white",
                  "edgecolor": LIGHT_BLUE, "alpha": 0.9})
    ax.set_title("Input-token growth as agent turns increase")
    ax.set_xlabel("Agent turns (T)")
    ax.set_ylabel("Predicted input tokens across one run")
    ax.set_xticks(turns)
    ax.set_ylim(0, max(totals) * 1.08)
    ax.grid(axis="y", alpha=0.25)
    ax.legend(frameon=False, loc="upper left", bbox_to_anchor=(0, 0.84))
    ax.text(0.01, -0.20,
            "Formula: B x T + D x T(T-1)/2. Measured B = {:,}; "
            "representative D = {} tokens/turn (median, parallel trajectories).".format(B, D),
            transform=ax.transAxes, fontsize=9, color="#444444")
    fig.tight_layout()
    save(fig, "fig_d0_turn_token_growth.png")


def reliability_curve_plot():
    """Connect D0 reliability to D6 cost using one measured operating point."""
    from d6_cost_model import FAILURE_COST, VOLUME_PER_MONTH

    p_measured = 60 / 90
    # Pair P and T from the same GPT-4o-mini live-trial distribution.
    t_measured = 8
    s = p_measured ** (1 / t_measured)
    l1 = measure_run(*RUNS["gpt-4o-mini"])["l1"]

    def monthly_cost(p):
        return VOLUME_PER_MONTH * (l1 + (1 - p) * FAILURE_COST)

    turns = [t / 2 for t in range(2, 33)]
    success = [100 * s ** t for t in turns]
    cost = [monthly_cost(s ** t) for t in turns]

    fig, (ax, ax2) = plt.subplots(1, 2, figsize=(12.5, 5.6), sharex=True)

    ax.plot(turns, success, color=NAVY, linewidth=2.5, zorder=4)
    ax.fill_between(turns, success, color=LIGHT_BLUE, alpha=0.28)
    offsets_left = {4: (-8, 14), t_measured: (10, 14), 12: (10, -30)}
    for turn in (4, t_measured, 12):
        p = s ** turn
        is_measured = (turn == t_measured)
        ax.scatter([turn], [100 * p], color=(CORAL if is_measured else BLUE),
                   s=100 if is_measured else 65, zorder=6,
                   edgecolor="white", linewidth=1.2)
        label = f"T={turn}: {100*p:.1f}%" + ("\n(measured)" if is_measured
                                              else "\n(predicted)")
        ax.annotate(label, (turn, 100 * p), xytext=offsets_left[turn],
                    textcoords="offset points", ha="left", fontsize=8.8,
                    fontweight="bold" if is_measured else "normal",
                    color=(CORAL if is_measured else NAVY))
    ax.axvline(t_measured, color=CORAL, linestyle="--", linewidth=1,
               alpha=0.75)
    ax.set_title("Predicted whole-run reliability", fontsize=11)
    ax.set_xlabel("Turns in one run (T)")
    ax.set_ylabel("Predicted whole-run success rate")
    ax.set_ylim(45, 102)
    ax.set_xlim(1, 16)
    ax.set_xticks(range(1, 17, 2))
    ax.yaxis.set_major_formatter(lambda v, _: f"{v:.0f}%")
    ax.grid(axis="y", alpha=0.2)

    ax2.plot(turns, cost, color=CORAL, linewidth=2.5, zorder=4)
    ax2.fill_between(turns, cost, color=CORAL, alpha=0.12)
    offsets_right = {4: (-8, 14), t_measured: (10, -30), 12: (10, 14)}
    for turn in (4, t_measured, 12):
        p = s ** turn
        is_measured = (turn == t_measured)
        ax2.scatter([turn], [monthly_cost(p)],
                    color=(CORAL if is_measured else BLUE),
                    s=100 if is_measured else 65, zorder=6,
                    edgecolor="white", linewidth=1.2)
        label = (f"T={turn}: USD {monthly_cost(p):,.0f}/mo"
                 + ("\n(measured P)" if is_measured else "\n(predicted)"))
        ax2.annotate(label, (turn, monthly_cost(p)), xytext=offsets_right[turn],
                     textcoords="offset points", ha="left", fontsize=8.8,
                     fontweight="bold" if is_measured else "normal",
                     color=(CORAL if is_measured else NAVY))
    ax2.axvline(t_measured, color=CORAL, linestyle="--", linewidth=1,
                alpha=0.75)
    ax2.set_title("Implied monthly cost from the same reliability curve",
                  fontsize=11)
    ax2.set_xlabel("Turns in one run (T)")
    ax2.set_ylabel("Implied monthly cost, 8,000 claims")
    ax2.set_ylim(0, max(cost) * 1.15)
    ax2.set_xticks(range(1, 17, 2))
    ax2.yaxis.set_major_formatter(lambda v, _: f"USD {v:,.0f}")
    ax2.grid(axis="y", alpha=0.2)

    fig.suptitle("Increasing turns compounds failure risk and expected cost",
                 fontsize=12.5, y=1.02)
    fig.text(0.01, -0.07,
             f"Both panels use paired GPT-4o-mini live-trial measurements "
             f"(P={p_measured:.3f}, T={t_measured}); T=4 and T=12 are "
             "predictions, not separate measurements.\n"
             f"Cost holds measured L1 at USD {l1:.4f}/run and uses Problem A's "
             "USD 7.60 failure cost; real turns are not independent or equally "
             "difficult.", fontsize=8.3, color="#444444")
    fig.tight_layout()
    save(fig, "fig_d0_reliability_curve.png")


def failure_reproduction_plot():
    """D7 before/after evidence in the report's shared visual language.

    Computed live from failure1_loop.py/failure2_interface.py rather than
    hardcoded - a hardcoded copy of these numbers went stale the moment
    config.TOOL_SPECS changed (D4's gate-fix work grew the system prompt),
    silently disagreeing with what the scripts themselves now report.
    """
    import failure1_loop
    import failure2_interface

    CHEAP_IN, CHEAP_OUT = 0.10, 0.40  # section 7, USD per million tokens

    def cost(inp, out):
        return inp / 1e6 * CHEAP_IN + out / 1e6 * CHEAP_OUT

    f1_broken = failure1_loop.run_once(max_repeats=999)
    f1_fixed = failure1_loop.run_once(max_repeats=config.MAX_REPEATS)
    f2_broken = failure2_interface.run_broken()
    f2_fixed = failure2_interface.run_fixed()

    fig, axes = plt.subplots(1, 2, figsize=(12.5, 5.6))

    # Failure 1 is detected by excess work even though the outcome still passes.
    states1 = ["Working", "Broken", "Restored"]
    turns1 = [f1_fixed.steps, f1_broken.steps, f1_fixed.steps]
    tokens1 = [f1_fixed.input_tokens_est, f1_broken.input_tokens_est,
               f1_fixed.input_tokens_est]
    costs1 = [cost(f1_fixed.input_tokens_est, f1_fixed.output_tokens_est),
              cost(f1_broken.input_tokens_est, f1_broken.output_tokens_est),
              cost(f1_fixed.input_tokens_est, f1_fixed.output_tokens_est)]
    colors1 = [BLUE, CORAL, NAVY]
    axes[0].bar(states1, turns1, color=colors1, width=0.58)
    axes[0].axhline(config.MAX_STEPS, color=CORAL, linestyle="--", linewidth=1,
                    alpha=0.75, label="{}-turn backstop".format(config.MAX_STEPS))
    axes[0].set_title("Failure 1: repeated action reaches the turn cap",
                      fontsize=11)
    axes[0].set_ylabel("Agent turns per run")
    axes[0].set_ylim(0, config.MAX_STEPS * 1.17)
    axes[0].grid(axis="y", alpha=0.2)
    axes[0].legend(frameon=False, loc="upper right")
    for i, (turns, tokens, c) in enumerate(zip(turns1, tokens1, costs1)):
        axes[0].text(i, turns + 0.35,
                     f"{turns} turns\n{tokens:,} input tok\nUSD {c:.5f}",
                     ha="center", va="bottom", fontsize=8.5,
                     fontweight="bold" if i == 1 else "normal",
                     color=CORAL if i == 1 else NAVY)

    # Failure 2 looks cheaper, so correctness—not efficiency—exposes it.
    states2 = ["Working", "Broken", "Restored"]
    tokens2 = [f2_fixed.input_tokens_est, f2_broken.input_tokens_est,
               f2_fixed.input_tokens_est]
    calls2 = [f2_fixed.tool_calls, f2_broken.tool_calls, f2_fixed.tool_calls]
    costs2 = [cost(f2_fixed.input_tokens_est, f2_fixed.output_tokens_est),
              cost(f2_broken.input_tokens_est, f2_broken.output_tokens_est),
              cost(f2_fixed.input_tokens_est, f2_fixed.output_tokens_est)]
    outcomes2 = ["approve", "WRONG escalate", "approve"]
    colors2 = [BLUE, CORAL, NAVY]
    axes[1].bar(states2, tokens2, color=colors2, width=0.58)
    axes[1].set_title("Failure 2: the wrong outcome appears cheaper",
                      fontsize=11)
    axes[1].set_ylabel("Input tokens per run")
    axes[1].set_ylim(0, max(tokens2) * 1.2)
    axes[1].grid(axis="y", alpha=0.2)
    for i, (tokens, calls, c, outcome) in enumerate(
            zip(tokens2, calls2, costs2, outcomes2)):
        axes[1].text(i, tokens + max(tokens2) * 0.02,
                     f"{tokens:,} input tok\n{calls} calls · USD {c:.6f}\n{outcome}",
                     ha="center", va="bottom", fontsize=8.5,
                     fontweight="bold" if i == 1 else "normal",
                     color=CORAL if i == 1 else NAVY)

    fig.suptitle("Broken-state reproductions locate two different failure layers",
                 fontsize=12.5, y=1.01)
    fig.text(0.01, -0.035,
             "Coral marks the deliberately broken implementation; blue and navy "
             "show the identical working and restored states. Failure 1 is exposed "
             "by instrumentation; Failure 2 only by the D4 outcome check.",
             fontsize=8.5, color="#444444")
    fig.tight_layout()
    save(fig, "fig_d7_failures.png")


def live_battery_summary_plot():
    """Compact Section 3 comparison of accuracy, Layer-1 cost and latency."""
    panels = [
        ("Trial pass rate",
         [("DeepSeek", 98.9), ("Gemini", 93.3), ("GPT-4o", 66.7),
          ("Qwen", 54.4), ("Llama", 36.7)], 100,
         lambda value: f"{value:.1f}%", "DeepSeek"),
        ("Mean AI cost / run",
         [("Gemini", 0.00566), ("GPT-4o", 0.00314), ("Qwen", 0.00203),
          ("DeepSeek", 0.00122), ("Llama", 0.00088)], 0.006,
         lambda value: f"${value:.5f}", "Llama"),
        ("Mean latency / run",
         [("DeepSeek", 54.2), ("Llama", 54.0), ("GPT-4o", 33.8),
          ("Qwen", 12.3), ("Gemini", 6.9)], 60,
         lambda value: f"{value:.1f}s", "Gemini"),
    ]

    fig, axes = plt.subplots(1, 3, figsize=(13.2, 3.5))
    for ax, (title, rows, maximum, formatter, highlight) in zip(axes, panels):
        ax.set_xlim(0, 1.58)
        ax.set_ylim(-0.65, len(rows) - 0.35)
        ax.axis("off")
        ax.set_title(title, loc="left", fontsize=12, fontweight="bold",
                     color=NAVY, pad=12)
        for index, (label, value) in enumerate(rows):
            y = len(rows) - 1 - index
            start, width = 0.50, 0.58
            ax.text(0, y, label, va="center", fontsize=10, color="#1F1F1F")
            ax.plot([start, start + width], [y, y], color="#E7EAF0",
                    linewidth=10, solid_capstyle="round", zorder=1)
            ax.plot([start, start + width * value / maximum], [y, y],
                    color=CORAL if label == highlight else NAVY,
                    linewidth=10, solid_capstyle="round", zorder=2)
            ax.text(1.16, y, formatter(value), va="center", ha="left",
                    fontsize=9.5, color="#1F1F1F")
        for spine in ax.spines.values():
            spine.set_visible(True)
            spine.set_color("#CBD3DF")
            spine.set_linewidth(0.7)
        ax.patch.set_visible(True)
        ax.patch.set_facecolor("white")

    fig.text(0.5, 0.01,
             "Measured trial accuracy, Layer-1 cost, and latency across the "
             "live battery, current 50-case set.",
             ha="center", fontsize=10.5, color="#555555", style="italic")
    fig.tight_layout(rect=(0.01, 0.08, 0.99, 0.98), w_pad=1.2)
    save(fig, "fig_d5b_cost_latency_accuracy.png")


def strict_case_rate(rows):
    by_case = {}
    for row in rows:
        by_case.setdefault(row["case_id"], []).append(row)
    return 100 * sum(all(r["passed"] for r in case)
                     for case in by_case.values()) / len(by_case)


def historical_d5_plots():
    before = json.loads(
        (RESULTS / "d5b_live_gpt4o_mini_full_battery.json").read_text())
    after = json.loads(
        (RESULTS / "d5b_live_validation_after_prompt_fix.json").read_text())
    before_rate, after_rate = strict_case_rate(before), strict_case_rate(after)
    before_turns = sorted(r["steps"] for r in before)[len(before) // 2]
    after_turns = sorted(r["steps"] for r in after)[len(after) // 2]

    fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))
    axes[0].bar(["before fix", "after fix"], [before_rate, after_rate],
                color=[CORAL, BLUE])
    axes[0].set_ylim(0, 100)
    axes[0].set_ylabel("strict case-consistency rate (%)")
    axes[0].set_title("D5(b) - GPT-4o-mini outcome consistency")
    for i, value in enumerate((before_rate, after_rate)):
        axes[0].text(i, value + 1, f"{value:.0f}%", ha="center")
    axes[1].bar(["before fix", "after fix"], [before_turns, after_turns],
                color=[CORAL, BLUE])
    axes[1].axhline(5, linestyle="--", color=GREY,
                    label="scripted assumption (5)")
    axes[1].set_ylabel("median turns")
    axes[1].set_title("D5(b) - median turns vs. scripted assumption")
    axes[1].legend()
    for i, value in enumerate((before_turns, after_turns)):
        axes[1].text(i, value + 0.1, str(value), ha="center")
    fig.tight_layout()
    save(fig, "fig_d5b_before_after.png")

    failures = [row for row in after if not row["passed"]]
    reasons = Counter(row.get("stop_reason") or "unknown" for row in failures)
    fig, ax = plt.subplots(figsize=(6.5, 4.5))
    labels, values = list(reasons), list(reasons.values())
    ax.bar(labels, values, color=CORAL)
    ax.set_ylabel("failing trials")
    ax.set_title("D5(b) - why the remaining failures happen")
    ax.tick_params(axis="x", rotation=18)
    for i, value in enumerate(values):
        ax.text(i, value + 0.15, str(value), ha="center")
    fig.tight_layout()
    save(fig, "fig_d5b_failure_reasons.png")


def descriptor_v1_v2_live_plot():
    """D2(b) live comparison - the original bubble-chart design, ported
    verbatim from A2_analysis.ipynb cell 2e794bff into this module so it is
    reproducible from one source instead of only existing in a notebook
    that has to be run by hand.
    """
    import matplotlib.patheffects as pe
    from matplotlib.colors import LinearSegmentedColormap

    modern_cmap = LinearSegmentedColormap.from_list(
        "modern", ["#E07A5F", "#A8C7DD", "#78A6C8"])

    v1_live = measure_run("openai/gpt-4o-mini", "d2b_live_v1_gpt4o_mini.json")
    v2_live = measure_run("openai/gpt-4o-mini", "d2b_live_v2_gpt4o_mini.json")

    fig, ax = plt.subplots(figsize=(7.5, 6))
    fig.patch.set_facecolor("#fbfbfd")
    ax.set_facecolor("#fbfbfd")

    xs = [v1_live["l1"], v2_live["l1"]]
    ys = [v1_live["latency"], v2_live["latency"]]
    x_pad = (max(xs) - min(xs)) * 1.6 or max(xs) * 0.2
    y_pad = (max(ys) - min(ys)) * 1.6 or max(ys) * 0.2
    xlim = (min(xs) - x_pad, max(xs) + x_pad)
    ylim = (min(ys) - y_pad, max(ys) + y_pad * 2.2)

    for label, d in [("v1 (vague)", v1_live), ("v2 (current)", v2_live)]:
        x, y, p = d["l1"], d["latency"], d["p"]
        size = 900 + p * 3800
        radius_pts = math.sqrt(size / math.pi)
        dy = radius_pts + 14
        ax.scatter(x, y, s=size * 1.12, color="#000000", alpha=0.06, zorder=2, linewidths=0)
        ax.scatter(x, y, s=size, c=[p], cmap=modern_cmap, vmin=0.5, vmax=0.8,
                   edgecolors="white", linewidths=2.5, alpha=0.95, zorder=3)
        ax.annotate(label, (x, y), xytext=(0, dy), textcoords="offset points",
                    ha="center", fontsize=11, fontweight="medium", color="#212529",
                    bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="#e9ecef", lw=0.8))
        ax.annotate("{:.0f}%".format(p * 100), (x, y), ha="center", va="center",
                    fontsize=11, fontweight="bold", color="white",
                    path_effects=[pe.withStroke(linewidth=2.5, foreground="#00000055")])

    ax.set_xlim(xlim)
    ax.set_ylim(ylim)
    for spine in ("top", "right"):
        ax.spines[spine].set_visible(False)
    for spine in ("left", "bottom"):
        ax.spines[spine].set_color("#ced4da")
    ax.tick_params(colors="#495057")
    ax.grid(axis="both", alpha=0.15, zorder=0)
    ax.set_xlabel("cost per run, USD", fontsize=11, color="#495057")
    ax.set_ylabel("average latency, seconds/run", fontsize=11, color="#495057")

    fig.suptitle("Descriptor v1 vs v2, openai/gpt-4o-mini",
                 fontsize=15, fontweight="bold", color="#212529", x=0.02, ha="left", y=1.02)
    ax.set_title("bubble size and colour = case-level pass rate", fontsize=10,
                 color="#868e96", loc="left", pad=12)

    sm = plt.cm.ScalarMappable(cmap=modern_cmap, norm=plt.Normalize(vmin=0.5, vmax=0.8))
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax, pad=0.03)
    cbar.set_label("case-level pass rate", color="#495057")
    cbar.ax.tick_params(colors="#495057")
    cbar.outline.set_visible(False)

    fig.tight_layout()
    fig.savefig(FIGS / "fig_d2b_live_v1_v2.png", bbox_inches="tight",
                facecolor=fig.get_facecolor(), dpi=180)
    plt.close(fig)
    print("plot written to", FIGS / "fig_d2b_live_v1_v2.png")


def d2c_per_case_plot():
    """D2(c) per-case token comparison, all cases in the CURRENT set."""
    rows, _ = measure_all()
    case_ids = [r["case_id"] for r in rows]
    par_tokens = [r["parallel"]["input_tokens_est"] for r in rows]
    seq_tokens = [r["sequential"]["input_tokens_est"] for r in rows]

    order_idx = sorted(range(len(rows)), key=lambda i: seq_tokens[i])
    sorted_ids = [case_ids[i] for i in order_idx]
    sorted_par = [par_tokens[i] for i in order_idx]
    sorted_seq = [seq_tokens[i] for i in order_idx]

    fig, ax = plt.subplots(figsize=(14, 5))
    x = range(len(sorted_ids))
    ax.bar([i - 0.2 for i in x], sorted_seq, width=0.4,
           label="sequential", color=CORAL)
    ax.bar([i + 0.2 for i in x], sorted_par, width=0.4,
           label="parallel", color=BLUE)
    ax.set_xticks(list(x))
    ax.set_xticklabels(sorted_ids, rotation=90, fontsize=7)
    ax.set_ylabel("input tokens (measured)")
    ax.set_title(
        "D2(c) - input tokens per case, parallel vs sequential "
        "(all {} cases)".format(len(rows)))
    ax.grid(axis="y", alpha=0.2)
    ax.legend(frameon=False)
    fig.tight_layout()
    save(fig, "fig_d2c_per_case.png")


def cost_sensitivity_plot():
    """D6 sensitivity: GPT-4o-mini's measured p, +-10 percentage points.

    This is what the report's Figure 6 caption ("Success-rate sensitivity
    around GPT-4o-mini") actually promises - the previous fig_d6_sensitivity
    .png instead showed the five-model monthly-cost ranking, a different
    chart under the caption's name.
    """
    base = measure_run(*RUNS["gpt-4o-mini"])
    p0 = base["p"]
    scenarios = [("Downside", max(0.0, p0 - 0.10)),
                 ("Measured", p0),
                 ("Upside", min(1.0, p0 + 0.10))]
    monthly = [monthly_cost(base["l1"], p) for _, p in scenarios]
    colors = [GREY, CORAL, GREY]

    fig, ax = plt.subplots(figsize=(7, 5))
    labels = [name for name, _ in scenarios]
    ax.bar(labels, monthly, color=colors, width=0.55)
    for i, ((_, p), m) in enumerate(zip(scenarios, monthly)):
        ax.text(i, m + max(monthly) * 0.015,
                "p={:.1%}\n${:,.0f}/mo".format(p, m), ha="center", fontsize=9)
    ax.set_ylabel("monthly cost, USD ({:,} claims/month)".format(VOLUME_PER_MONTH))
    ax.set_title("D6 - cost sensitivity to success rate, GPT-4o-mini +-10pp")
    ax.set_ylim(0, max(monthly) * 1.2)
    ax.grid(axis="y", alpha=0.2)
    fig.tight_layout()
    save(fig, "fig_d6_sensitivity.png")


def monthly_cost_by_model_plot():
    """D6 monthly cost across all five models - horizontal bars, ranked
    cheapest first, one label per bar (cost + measured pass rate), with the
    formula stated on the chart. A different question from
    cost_sensitivity_plot() (which stress-tests ONE model's accuracy
    estimate): this one compares ACROSS models, at each model's own
    measured pass rate, so the two are not substitutes for each other.
    """
    measured = {name: measure_run(model, fname) for name, (model, fname) in RUNS.items()
                if "v1 prompt" not in name}
    ranked = sorted(measured.items(), key=lambda kv: kv[1]["l1"] + layer2_fallback(kv[1]["p"]))
    names = [n for n, _ in ranked][::-1]  # cheapest at top of a horizontal chart
    data = [d for _, d in ranked][::-1]
    monthly = [monthly_cost(d["l1"], d["p"]) for d in data]
    # names/data/monthly are ordered most-expensive-first (index 0) so that,
    # with barh's y=0-at-bottom convention, the cheapest model (last index)
    # lands at the TOP of the chart - so the highlight goes on the LAST bar.
    colors = [NAVY] * (len(names) - 1) + [CORAL]

    fig, ax = plt.subplots(figsize=(9.5, 5.2))
    y = range(len(names))
    bars = ax.barh(list(y), monthly, color=colors, height=0.6)
    ax.set_yticks(list(y))
    ax.set_yticklabels(names, fontsize=11)
    ax.set_xlabel("Expected monthly cost, USD ({:,} claims/month)".format(VOLUME_PER_MONTH))
    ax.grid(axis="x", alpha=0.25)
    for spine in ("top", "right", "left"):
        ax.spines[spine].set_visible(False)
    max_m = max(monthly)
    for yi, (name, d, m) in enumerate(zip(names, data, monthly)):
        ax.text(m + max_m * 0.015, yi, "${:,.0f}/mo  |  Pass: {:.1%}".format(m, d["p"]),
                va="center", fontsize=10.5, color=NAVY)
    ax.set_xlim(0, max_m * 1.32)
    fig.text(0.01, 0.01,
             "Expected monthly cost = V x [C_AI + (1-p) x C_fallback] + F   "
             "(V = claim volume, p = trial-level pass rate; human fallback dominates token cost)",
             fontsize=9.5, color="#444444")
    fig.suptitle("Claims First-Response Agent: Expected Monthly Cost by Model",
                 fontsize=15, fontweight="bold", x=0.01, ha="left", y=0.99)
    # Escape literal "$" - matplotlib's mathtext treats a PAIR of $ as an
    # equation span and silently drops the spaces inside it otherwise.
    fig.text(0.01, 0.925,
             "Assumptions: {:,} claims/month  |  \\${:.2f} human fallback per failed claim  |  "
             "\\$5 monthly regression testing".format(VOLUME_PER_MONTH, 7.60),
             fontsize=10.5, color=GREY)
    fig.tight_layout(rect=(0, 0.05, 1, 0.90))
    save(fig, "fig_d6_monthly_by_model.png")


def breakeven_plot():
    """D6 break-even success rate, benchmarked against whichever model is
    CURRENTLY cheapest overall - computed the same way d6_cost_model.py
    picks it (a min() over measured total cost/task), not a hardcoded name.
    The previous version of this figure hardcoded "gemini-2.5-flash" as the
    benchmark; deepseek-v4-flash overtook it on the current 50-case
    measurement and the figure was never regenerated, so it silently
    disagreed with the report's own text and tables.
    """
    measured = {name: measure_run(model, fname)
                for name, (model, fname) in RUNS.items()
                if "v1 prompt" not in name}
    exp_name = min(measured, key=lambda n: measured[n]["l1"] + layer2_fallback(measured[n]["p"]))
    exp = measured[exp_name]

    cheaper = [(n, d) for n, d in measured.items() if n != exp_name]
    cheaper.sort(key=lambda kv: kv[1]["p"])
    be_names = [n for n, _ in cheaper]
    current_p = [d["p"] * 100 for _, d in cheaper]
    break_even_p = [break_even_success_rate(d["l1"], exp["p"], exp["l1"]) * 100
                    for _, d in cheaper]

    fig, ax = plt.subplots(figsize=(8, 5))
    x = list(range(len(be_names)))
    ax.bar([i - 0.2 for i in x], current_p, width=0.4,
           label="currently at", color=BLUE)
    ax.bar([i + 0.2 for i in x], break_even_p, width=0.4,
           label="needs to reach", color=NAVY)
    ax.axhline(exp["p"] * 100, linestyle="--", color=GREY, linewidth=1.3,
               label="{}'s own p ({:.1f}%)".format(exp_name, exp["p"] * 100))
    for i, (now, be) in enumerate(zip(current_p, break_even_p)):
        ax.text(i - 0.2, now + 1.5, "{:.1f}%".format(now), ha="center", fontsize=8.5)
        ax.text(i + 0.2, be + 1.5, "{:.1f}%".format(be), ha="center", fontsize=8.5)
        # The story here is the GAP, not the bar heights - every "needs to
        # reach" bar sits near the benchmark's own p almost by construction
        # (failure cost swamps token price), so an unlabelled reader can
        # easily mistake four near-identical bars for a rendering error
        # rather than the actual finding. Spell the gap out explicitly.
        ax.annotate("", xy=(i, be + 1.5), xytext=(i, now - 1.5),
                    arrowprops=dict(arrowstyle="-|>", color=CORAL, linewidth=1.4,
                                     shrinkA=0, shrinkB=0))
        ax.text(i, (now + be) / 2 - 6, "+{:.1f}pp".format(be - now),
                ha="center", fontsize=9, fontweight="bold", color=CORAL)
    ax.set_xticks(x)
    ax.set_xticklabels(be_names, rotation=20, ha="right")
    ax.set_ylabel("success rate (%)")
    ax.set_title(
        "D6 - break-even p to match {}'s total cost/task".format(exp_name),
        pad=12)
    ax.set_ylim(0, 128)
    ax.legend(frameon=True, facecolor="white", edgecolor="#DDDDDD",
              loc="upper right", fontsize=9)
    ax.grid(alpha=0.2, axis="y")
    fig.tight_layout()
    save(fig, "fig_d6_breakeven.png")


def main():
    completed_task_cost_plot()
    turn_token_growth_plot()
    reliability_curve_plot()
    failure_reproduction_plot()
    live_battery_summary_plot()
    historical_d5_plots()
    descriptor_v1_v2_live_plot()
    d2c_per_case_plot()
    cost_sensitivity_plot()
    monthly_cost_by_model_plot()
    breakeven_plot()


if __name__ == "__main__":
    main()
